version: 0.0.0
description: NFT Factory
repository: https://github.com/nft-factory
networks:
  - id: 31337
    rpc_url: http://localhost:8545
    start_block: 0
    contracts:
      - name: NftFactory
        abi_file_path: abis/NftFactory.json
        address: ["0x5FbDB2315678afecb367f032d93F642f64180aa3"]
        handler: src/EventHandlers.ts
        events:
          - name: "SimpleNftCreated"
            requiredEntities: []
      - name: SimpleNft
        abi_file_path: abis/SimpleNft.json
        address: ["0xa16E02E87b7454126E5E10d957A927A7F5B5d2be"]
        handler: src/EventHandlers.ts
        events:
          - name: "Transfer"
            requiredEntities:
              - name: "User"
                labels:
                  - "userFrom"
                  - "userTo"
              - name: Nftcollection
                labels:
                  - "nftCollectionUpdated"
              - name: Token
                labels:
                  - "existingTransferredToken"
