name: erc20indexer
description: ERC-20 indexer
networks:
  - id: 5 # Goerli Testnet
    start_block: 9493714
    contracts:
      - name: ERC20
        address: ["0x61cce07e4cad3bf797667f8fd14d2a7d1582038e"]
        handler: src/EventHandlers.ts
        events:
          - event: "Approval(address indexed owner, address indexed spender, uint256 value)"
            requiredEntities:
              - name: "Account"
              - name: "Approval"
          - event: "Transfer(address indexed from, address indexed to, uint256 value)"
            requiredEntities:
              - name: "Account"
              - name: "Approval"
  # # NOTE: for a more exciting indexer with lots of events, replace above with the following to index the UNI token
  # - id: 1 # Ethereum Mainnet
  #   start_block: 10861674
  #   contracts:
  #     - name: ERC20
  #       address: "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984" #UNI
  #       handler: src/EventHandlers.ts
  #       events:
  #         - event: "Approval(address indexed owner, address indexed spender, uint256 value)"
  #           requiredEntities:
  #             - name: "Account"
  #             - name: "Approval"
  #         - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  #           requiredEntities:
  #             - name: "Account"
  #             - name: "Approval"
