name: erc20indexer
description: ERC-20 indexer
networks:
  - id: 5 # Goerli Testnet
    start_block: 9493714
    contracts:
      - name: ERC20
        abi_file_path: abis/ERC20.json
        address: ["0x61cce07e4cad3bf797667f8fd14d2a7d1582038e"]
        handler: src/EventHandlers.ts
        events:
          - event: "Approval"
            requiredEntities:
              - name: "Account"
                labels:
                  - "ownerAccountChanges"
          - event: "Transfer"
            requiredEntities:
              - name: "Account"
                labels:
                  - "senderAccountChanges"
                  - "receiverAccountChanges"
