version: 0.0.0
description: Greeter indexer
repository: https://github.com/PaulRBerg/hardhat-template
networks:
  - id: 1337
    rpc_url: http://localhost:8545
    start_block: 0
    contracts:
      - name: Greeter
        abi_file_path: abis/greeter-abi.json
        address: ["0x5FbDB2315678afecb367f032d93F642f64180aa3"]
        handler: ./src/EventHandlers.bs.js
        events:
          - name: "Greeting"
            requiredEntities: [] # empty signifies no requirements
