version: 0.0.2
description: Gravatar for Ethereum
repository: https://github.com/graphprotocol/example-subgraph
networks: 
    - network:
      - id: 137
      - rpc-url: https://polygon-rpc.com
      - start-block: 34316032
    
contracts:
  - contract:  
    - name: Gravatar
    - abi: 
        - "event NewGravatar(uint256,address,string,string)"
        - "event UpdatedGravatar(uint256,address,string,string)"
    - address: 0x2E645469f354BB4F5c8a05B3b30A929361cf77eC
    - events: 
      - NewGravatar  
      - UpdatedGravatar  

#From The Graph Example
#
# specVersion: 0.0.2
# description: Gravatar for Ethereum
# repository: https://github.com/graphprotocol/example-subgraph
# schema:
#   file: ./schema.graphql
# dataSources:
#   - kind: ethereum/contract
#     name: Gravity
#     network: mainnet
#     source:
#       address: '0x2E645469f354BB4F5c8a05B3b30A929361cf77eC'
#       abi: Gravity
#     mapping:
#       kind: ethereum/events
#       apiVersion: 0.0.5
#       language: wasm/assemblyscript
#       entities:
#         - Gravatar
#       abis:
#         - name: Gravity
#           file: ./abis/Gravity.json
#       eventHandlers:
#         - event: NewGravatar(uint256,address,string,string)
#           handler: handleNewGravatar
#         - event: UpdatedGravatar(uint256,address,string,string)
#           handler: handleUpdatedGravatar
#       file: ./src/mapping.ts
