name: ERC20
description: ERC-20 indexer
networks:
  - id: 1 # Ethereum Mainnet
    rpc_config:
      url: https://eth.llamarpc.com # We recommend you change this to a dedicated RPC provider
    start_block: 16800000
    contracts:
      - name: ERC20
        abi_file_path: abis/erc20.json
        address: ["0x2B2f78c5BF6D9C12Ee1225D5F374aa91204580c3"]
        handler: ./src/EventHandlers.js
        events:
          - event: "Approval"
            requiredEntities:
              - name: "Account"
                labels:
                  - "ownerAccountChanges"
          - event: "Transfer"
            requiredEntities:
              - name: "Account"
                labels:
                  - "senderAccountChanges"
                  - "receiverAccountChanges"
