version: 0.0.0
description: Simple Bank contract
repository: 
networks:
  - id: 31337
    rpc_url: http://localhost:8545
    start_block: 0
    contracts:
      - name: SimpleBank
        abi_file_path: abis/SimpleBank.json
        address: ["0x2B2f78c5BF6D9C12Ee1225D5F374aa91204580c3"]
        handler: build/src/EventHandlers.ts
        events:
          - name: "DepositMade"
            requiredEntities: # empty signifies no requirements
              - name: "User"
                labels:
                  - "userBalanceChanges"
          - name: "WithdrawalMade"
            requiredEntities: # if this field isn't specified it should default to include all entities
              - name: "User"
                labels:
                  - "userBalanceChanges"
          - name: "TotalBalanceChanged"
            requiredEntities: # if this field isn't specified it should default to include all entities
              - name: "User"
                labels:
                  - "userBalanceChanges"
              - name: "Bank"
                labels:
                  - "totalBalanceChanges"
