version: 0.0.0
description: Simple Bank contract
repository: 
networks:
  - id: 31337
    rpc_url: http://localhost:8545
    start_block: 0
    contracts:
      - name: SimpleBank
        abi_file_path: contracts/abis/SimpleBank.json
        address: ["0xa2F6E6029638cCb484A2ccb6414499aD3e825CaC"]
        handler: src/EventHandlers.js
        events:
          - name: "AccountCreated"
            requiredEntities: [] # empty signifies no requirements
          - name: "DepositMade"
            requiredEntities: 
              - name: "Account"
                labels:
                  - "accountBalanceChanges"
          - name: "WithdrawalMade"
            requiredEntities: # if this field isn't specified it should default to include all entities
              - name: "Account"
                labels:
                  - "accountBalanceChanges"
          - name: "TotalBalanceChanged"
            requiredEntities: # if this field isn't specified it should default to include all entities
              - name: "Account"
                labels:
                  - "accountBalanceChanges"
              - name: "Bank"
                labels:
                  - "totalBalanceChanges"
