version: 1.0.0
description: ERC-20 indexer
repository: https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/token/ERC20
networks:
  - id: 1337
    rpc_url: http://localhost:8545
    start_block: 0
    contracts:
      - name: ERC20
        abi_file_path: abis/ERC20.json
        address: ["0x2B502ab6F783c2Ae96A75dc68cf82a77ce2637c2"]
        handler: ./src/EventHandlers.bs.js
        events:
          - name: "Approval"
            requiredEntities: []
          - name: "Creation"
            requiredEntities: 
            - name: "Erc20Token"
              labels:
                  - "erc20tokenCreation"
          - name: "Transfer"
            requiredEntities:
            - name: "TotalTransfers"
              labels:
              - "totalTransferChanges"
