name: erc20indexer
description: ERC-20 indexer
networks:
  - id: 1 # Ethereum Mainnet
    rpc_config:
      url: https://rpc.ankr.com/eth_goerli # We recommend you change this to a dedicated RPC provider
    start_block: 9493714
    contracts:
      - name: ERC20
        abi_file_path: abis/ERC20.json
        address: ["0x61cce07e4cad3bf797667f8fd14d2a7d1582038e"]
        handler: ./src/EventHandlers.bs.js
        events:
          - event: "Approval"
            requiredEntities:
              - name: "Account"
                labels:
                  - "ownerAccountChanges"
          - event: "Transfer"
            requiredEntities:
              - name: "Account"
                labels:
                  - "senderAccountChanges"
                  - "receiverAccountChanges"
