name: erc20indexer
description: ERC-20 indexer
networks:
  - id: 1 # Ethereum Mainnet
    rpc_config:
      url: https://eth.llamarpc.com # We recommend you change this to a dedicated RPC provider
    start_block: 16800000
    contracts:
      - name: ERC20
        abi_file_path: abis/ERC20.json
        address: ["0xc3761EB917CD790B30dAD99f6Cc5b4Ff93C4F9eA"]
        handler: ./src/EventHandlers.bs.js
        events:
          - event: "Approval"
            requiredEntities:
              - name: "Account"
                labels:
                  - "ownerAccountChanges"
          - event: "Transfer"
            requiredEntities:
              - name: "Account"
                labels:
                  - "senderAccountChanges"
                  - "receiverAccountChanges"
