name: erc20indexer
version: 1.0.0
description: ERC-20 indexer
networks:
  - id: 1337
    rpc_config:
      url: http://localhost:8545
    start_block: 0
    contracts:
      - name: ERC20
        abi_file_path: abis/ERC20.json
        address: ["0x2B2f78c5BF6D9C12Ee1225D5F374aa91204580c3"]
        handler: ./src/EventHandlers.bs.js
        events:
          - event: "Approval"
            requiredEntities:
              - name: "Account"
                labels:
                  - "ownerAccountChanges"
          - event: "Transfer"
            requiredEntities:
              - name: "Account"
                labels:
                  - "senderAccountChanges"
                  - "receiverAccountChanges"
