name: lens
description: Lens Protocol (decentralized, non-custodial social graph)
networks:
  - id: 137
    rpc_config: https://polygon-rpc.com
    start_block: 34316032

contracts:
  - name: LensProtocolProfiles
    abi: abis/gravatar-abi.json
    address: "0xDb46d1Dc155634FbC732f92E853b10B288AD5a1d"
    events:
      - name: "Transfer"
