version: 0.0.0
description: Gravatar for Ethereum
repository: https://github.com/graphprotocol/example-subgraph
networks:
  - id: 137
    rpc_url: https://polygon-rpc.com
    start_block: 34316032
    contracts:
      - name: Gravatar
        abi: abis/gravatar-abi.json
        address: "0x2E645469f354BB4F5c8a05B3b30A929361cf77eC"
        handler: ./src/EventHandlers.bs.js
        events:
          - name: "NewGravatar"
            requiredEntities: [] # empty signifies no requirements
          - name: "UpdatedGravatar"
            requiredEntities: # if this field isn't specified it should default to include all entities
              - name: "Gravatar"
                allowArbitrary: false # this defauls to false
                labels:
                  - "gravatarWithChanges"
