name: test_codegen
description: Gravatar for Ethereum
networks:
  - id: 1337
    rpc_config:
      url: http://localhost:8545 # RPC URL that will be used to subscribe to blockchain data on this network
      unstable__sync_config:
        initial_block_interval: 10000
        backoff_multiplicative: 0.8
        acceleration_additive: 2000
        interval_ceiling: 10000
        backoff_millis: 5000
        query_timeout_millis: 20000
    start_block: 1
    contracts:
      - name: Gravatar
        abi_file_path: abis/gravatar-abi.json
        address: "0x2B2f78c5BF6D9C12Ee1225D5F374aa91204580c3" # -> use this if you want to deploy to local ganache
        handler: ./src/EventHandlers.bs.js
        events:
          - event: "TestEventWLongNameDoesntWork(address testField)"
          - event: "TestEvent"
            requiredEntities:
              - name: "A"
                arrayLabels:
                  - "all"
          - event: "NewGravatar"
            requiredEntities: [] # empty signifies no requirements
          - event: "UpdatedGravatar"
            requiredEntities: # if this field isn't specified it should default to include all entities
              - name: "Gravatar"
                labels:
                  - gravatarWithChanges
      - name: NftFactory
        abi_file_path: abis/NftFactory.json
        address: "0xa2F6E6029638cCb484A2ccb6414499aD3e825CaC"
        handler: src/EventHandlers.ts
        events:
          - event: "SimpleNftCreated"
            requiredEntities: []
      - name: SimpleNft
        abi_file_path: abis/SimpleNft.json
        address: null
        handler: src/EventHandlers.ts
        events:
          - event: "Transfer"
            requiredEntities:
              - name: "User"
              - name: NftCollection
              - name: Token
