version: 0.0.0
description: Gravatar for Ethereum
repository: https://github.com/graphprotocol/example-subgraph
networks:
  - id: 1337
    rpc_url: http://localhost:8545
    start_block: 0
    contracts:
      - name: Gravatar
        abi_file_path: abis/gravatar-abi.json
        address: ["0x5FbDB2315678afecb367f032d93F642f64180aa3"] # for test suite on hardhat
        # address: ["0x2B2f78c5BF6D9C12Ee1225D5F374aa91204580c3"] -> use this if you want to deploy to local ganache
        handler: ./src/EventHandlers.bs.js
        events:
          - name: "NewGravatar"
            requiredEntities: [] # empty signifies no requirements
          - name: "UpdatedGravatar"
            requiredEntities: # if this field isn't specified it should default to include all entities
              - name: "Gravatar"
                labels:
                  - "gravatarWithChanges"
