name: My Awesome Contract Indexer # Name of the project
version: 0.0.1 # Version of the config schema used by the indexer
description: My Awesome Contract # Description of the project
repository:  # Repository of the project
networks: # Configuration of the blockchain networks that the project is deployed on
  - id: 1337 # Chain identifier of the network
    rpc_config: 
      url: http://localhost:8545 # RPC URL that will be used to subscribe to blockchain data on this network
    start_block: 0 # Initial block from which the indexer will start listening for events
    contracts: # Configuration for each contract 
      - name: MyAwesomeContract # User-defined contract name
        abi_file_path: abi/MyAwesomeContract.json # File location of the contract ABI
        address: "0x0000000000000000000000000000000000000000" # An array of addresses that the contract is deployed to on the network
        handler: ./src/EventHandlers.js # Location of the file that handles the events emitted by this contract
        events: # Configuration for each event emitted by this contract that the indexer will listen for
          - event: AwesomeEvent #  Name of the event (must match the name in the ABI)
            requiredEntities: # An array of entities that need to loaded and made accessible within the handler function (an empty array indicates that no entities are required)
              - name: AwesomeEntity # The name of the required entity (must match an entity defined in `schema.graphql`)
                labels: # A user defined label that corresponds to this entity load
                  - awesomeEntityChanges
