name: Benchmark Suite

on: push

defaults:
  run:
    working-directory: scenarios/gravatar

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install pnpm
        run: npm install -g pnpm

      - name: generate code
        run: |
          cd ../../codegenerator
          cargo run -- codegen -d ../scenarios/gravatar

       # TODO: add pnpm caching
      - name: Install dependencies
        run: pnpm install

      - name: Build code
        run: |
          pnpm clean # probably not needed, but getting different results in pipeline to locally.
          pnpm build

      - name: Run benchmarks
        run: npx jest --projects jest-bench.config.json  
