name: Benchmark Suite

on: push

defaults:
  run:
    working-directory: scenarios/gravatar

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
        
      - name: generate code
        run: |
          cd ../../codegenerator
          cargo run -- codegen -d ../scenarios/gravatar

      # TODO: add pnpm caching
      - name: Install dependencies
        run: |
          pnpm install
          npm i -D jest-bench
          npm install jest-environment-node --save-dev

      - name: Build code
        run: |
          pnpm clean # probably not needed, but getting different results in pipeline to locally.
          pnpm build

      - name: Run benchmarks
        run: npx jest --projects jest-bench.config.json  
