name: Build & Test

on: pull_request

defaults:
  run:
    working-directory: codegenerator

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            ~/.cargo/registry
            ~/.cargo/git
            codegenerator/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: gravatar build, test & bench
        working-directory: scenarios/gravatar
        run: |
          pnpm codegen
          pnpm install
          pnpm build
          pnpm test
          pnpm bench

      - name: gravatar build, test & bench
        working-directory: scenarios/test_codegen
        run: |
          pnpm codegen
          pnpm install
          pnpm build
