# Starting pipeline - all in one for now

name: Indexer test
on: pull_request

# For now we just run this in the gravatar folder.
defaults:
  run:
    working-directory: scenarios/gravatar

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:13
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: testing
          POSTGRES_DB: indexly-dev
          POSTGRES_USER: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7
      

      - name: generate code
        run: |
          cd ../../codegenerator
          cargo run -- codegen -d ../scenarios/gravatar

      # TODO: add pnpm caching
      - name: Install dependencies
        run: pnpm install

      - name: Build code
        run: |
          pnpm clean # probably not needed, but getting different results in pipeline to locally.
          pnpm build

      - name: Run tests
        run: |
          PG_HOST="postgres" pnpm test
